# Generated by Django 5.1.7 on 2025-04-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edubuddy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edubuddyuser',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='edubuddyuser',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
