# Generated by Django 5.1.7 on 2025-04-13 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edubuddy', '0003_role_edubuddyuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='materials/')),
                ('is_processed', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('Primary School', 'Primary School'), ('High School', 'High School'), ('College', 'College')], max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
