# Generated by Django 5.1.7 on 2025-04-28 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edubuddy', '0007_category_alter_material_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edubuddy.category'),
        ),
    ]
