# Generated by Django 5.1.7 on 2025-04-28 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edubuddy', '0008_alter_material_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='edubuddy.category'),
        ),
    ]
